# Generated by Django 5.1 on 2024-08-30 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('email', models.EmailField(max_length=254, verbose_name='Inquirer E-Mail')),
                ('subject', models.CharField(max_length=50, verbose_name='Inquiry Subject')),
                ('text', models.TextField(max_length=2500, verbose_name='Inquiry Text')),
            ],
        ),
    ]
