# Generated by Django 5.1 on 2024-08-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Inquiry Processed'),
        ),
    ]
