# Generated by Django 5.1 on 2024-08-28 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0008_delete_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price of Order')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Order')),
                ('stripe_checkout_id', models.CharField(max_length=50, verbose_name='Stripe Checkout ID')),
                ('payment_complete', models.BooleanField(default=False, verbose_name='Paymant Complete')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.guide', verbose_name='Guide ordered')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who ordered')),
            ],
        ),
    ]
