# Generated by Django 5.1 on 2024-08-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='blog/', verbose_name='HTML File'),
        ),
    ]
