# Generated by Django 5.1 on 2024-08-23 19:52

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_html_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='html_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/ok/Documents/Python/guidehub/GuideHub/blog/templates/blog')), upload_to='', verbose_name='HTML File'),
        ),
    ]
