# Generated by Django 5.1 on 2024-08-19 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_pdf',
            field=models.FileField(upload_to='guide/doc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Full Guide PDF'),
        ),
    ]
