# Generated by Django 5.1 on 2024-08-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='guide/static/guide/img/', verbose_name='Thumbnal'),
        ),
    ]
