# Generated by Django 5.1 on 2024-08-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_guide_is_active_guide_stripe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Strip Product ID'),
        ),
    ]
