# Generated by Django 5.1 on 2024-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_alter_guide_guide_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='language',
            field=models.CharField(default='deutsch', max_length=7, verbose_name='Language'),
        ),
    ]
