# Generated by Django 5.1 on 2024-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_guide_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stripe Price ID'),
        ),
    ]
