# Generated by Django 5.1 on 2024-08-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_guide_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='stripe_payment_link_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stripe PaymentLink ID'),
        ),
    ]
