# Generated by Django 5.1 on 2024-08-23 20:29

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_guide_guide_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/ok/Documents/Python/guidehub/GuideHub/guide/doc')), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Full Guide PDF'),
        ),
    ]
