# Generated by Django 5.1 on 2024-08-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_guide_stripe_payment_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_complete',
            field=models.BooleanField(default=False, verbose_name='Paymant Complete'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stripe Checkout ID'),
        ),
    ]
