# Generated by Django 5.1 on 2024-08-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_alter_order_stripe_checkout_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
