# Generated by Django 5.1 on 2024-08-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='stripe_payment_link_id',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='stripe_url',
        ),
    ]
